name: nightly-publish
on:
  # schedule:
  #   - cron: '0 9 * * *'
  workflow_dispatch:
jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4

      - name: Check for changes last 24 hours
        id: should_run
        shell: bash
        run: |
          git log --since="1 days ago" --name-only
          echo "should_run=$(git log --since="1 days ago" --name-only | grep "" -c)" >> "$GITHUB_OUTPUT"

  publish:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.should_run >= 1 }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Copy to Pack Folder
        shell: bash
        run: |
          mkdir ${{ github.workspace }}/to-pack
          cp -r Docs/ ${{ github.workspace }}/to-pack/Docs/
      
      - name: Fetch spriggit
        shell: bash
        run: gh release download -O .github/spriggit.zip -p 'SpriggitLinuxCLI.zip' -R Mutagen-Modding/Spriggit ${{ inputs.spriggit_tool_version }}
        env:
          GH_TOKEN: ${{ github.token }}
          
      - name: Extract Spriggit Zip
        shell: bash
        run: 7z x .github/spriggit.zip -o.github/spriggit

      - name: fix spriggit permission
        shell: bash
        run: chmod +x .github/spriggit/Spriggit.CLI

      - name: run spriggit
        shell: bash
        run: .github/spriggit/Spriggit.CLI deserialize --InputPath "spriggit" --OutputPath "${{ github.workspace }}/to-pack/StarfieldCommunityPatch.esm"
        
      - name: zip
        uses: vimtor/action-zip@v1
        with:
          files: to-pack/
          dest: StarfieldCommunityPatch.zip

      - name: Delete Existing Release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: nightly
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true
          
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          name: Nightly
          draft: false
          body: Nightly release of the latest patch
          tag: nightly
          prerelease: true
          makeLatest: true
          removeArtifacts: true
          replacesArtifacts: true
          artifacts: StarfieldCommunityPatch.zip
